Add prettier config
middleporch/middlechat pull request #2
Opened 2022-03-08 18:36 UTC by elbojoloco

This is just a basic setup, we can upgrade to an eslint integrated prettier setup in the future if need be. Feel free to suggest changes to this config.

2022-03-08 18:53 UTC, elbojoloco commented
Integrating prettier with eslint instead

2022-03-09 14:11 UTC, jacobzlogar approved these changes

2022-03-09 14:29 UTC, Riari approved these changes

2022-03-09 14:40 UTC, lloy0076 requested changes
Please make a way for this all values relating to indent to be cryptographically secure random integers between 1 and at minimum 2^^256.

2022-03-09 14:54 UTC, Riari commented
<img width="730" alt="image" src="https://user-images.githubusercontent.com/3583774/157466525-ed51d098-b0d9-4ebe-bfa3-7d3e7a51af74.png">

2022-03-09 15:26 UTC, merged